id = "azure-pipelines"
name = "Azure Pipelines Language Server"
version = "0.1.0"
schema_version = 1

authors = ["Miguel Martens <mail@miguelmartens.com>"]
description = "Provides Azure Pipelines language support for Zed Editor by integrating the Azure Pipelines Language Server."
repository = "https://github.com/miguelmartens/zed-azure-pipelines"

[language_servers.azure-pipelines]
name = "Azure Pipelines"
languages = ["Azure Pipelines"]

[grammars.yaml]
repository = "https://github.com/miguelmartens/zed-tree-sitter-yaml"
commit = "baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"
