name = "Azure Pipelines"
# Using the YAML grammar since a dedicated Azure Pipelines grammar is not available.
# #grammar = "azure-pipelines"
grammar = "yaml"
# File suffixes that Zed will use to recognize Azure Pipelines files.
path_suffixes = ["azure-pipelines", "pipelines"]
# A heuristic to match files via their first line, if needed.
first_line_pattern = '^#!.*azure[- ]?pipelines'
line_comments = ["# "]

# Characters that trigger auto-closing of brackets/quotes.
autoclose_before = ",]}"

# Define bracket pairs and their behaviors.
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
    ] },
]

# Auto-indent settings.
auto_indent_using_last_non_empty_line = false
increase_indent_pattern = ":\\s*[|>]?\\s*$"

# Use the YAML parser for formatting.
prettier_parser_name = "yaml"
tab_size = 2
